TYPE_ORDER = [
    'Animal incident',
    'Epidemic',
    'Infestation',
    'Drought',
    'Glacial lake outburst flood',
    'Wildfire',
    'Impact',
    'Space weather',
    'Earthquake',
    'Mass movement (dry)',
    'Volcanic activity',
    'Flood',
    'Mass movement (wet)',
    'Wave action',
    'Extreme temperature',
    'Fog',
    'Storm',
    'Chemical spill',
    'Collapse (Industrial)',
    'Explosion (Industrial)',
    'Fire (Industrial)',
    'Gas leak',
    'Industrial accident (General)',
    'Oil spill',
    'Poisoning',
    'Radiation',
    'Collapse (Miscellaneous)',
    'Explosion (Miscellaneous)',
    'Fire (Miscellaneous)',
    'Miscellaneous accident (General)',
    'Air',
    'Rail',
    'Road',
    'Water'
]

TYPE_COLORS = {
    'Animal incident': '#4A8179',
    'Epidemic': '#ABD20E',
    'Infestation': '#8A935D',
    'Drought': '#D88804',
    'Glacial lake outburst flood': '#C3FCF1',
    'Wildfire' :'#C25452',
    'Impact': '#5C1274',
    'Space weather': '#74328B',
    'Earthquake': '#A06963',
    'Mass movement (dry)': '#EDDFDE',
    'Volcanic activity': '#B64621',
    'Flood': '#2A2D92',
    'Mass movement (wet)': '#4C43A5',
    'Wave action': '#0079C7',
    'Extreme temperature': '#FF9F90',
    'Fog': '#E9EFFF',
    'Storm': '#6B7190',
    'Chemical spill': '#2F4858',
    'Collapse (Industrial)': '#334A70',
    'Explosion (Industrial)': '#A71A5C',
    'Fire (Industrial)': '#BA0C2F',
    'Gas leak': '#813678',
    'Industrial accident (General)': '#55457E',
    'Oil spill': '#897270',
    'Poisoning': '#416800',
    'Radiation': '#779B00',
    'Collapse (Miscellaneous)': '#B3B3B3',
    'Explosion (Miscellaneous)': '#838383',
    'Fire (Miscellaneous)': '#565656',
    'Miscellaneous accident (General)': '#E6E6E6',
    'Air': '#008B9D',
    'Rail': '#8DF8B7',
    'Road': '#53BF82',
    'Water': '#088950'
}